config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), # pybo/로 시작하는 페이지를 요청하면 pybo/urls.py 파일의 매핑 정보를 읽어서 처리해라
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo' # 추후 다른 앱의 URL별칭과 겹칠 수 있으므로 네임스페이스를 의미하는 app_name 변수 지정

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

pybo/models.py
from django.db import models

# Create your models here.
class Question(models.Model): # id는 자동으로 매겨지므로 생성 안해도 됨
    subject = models.CharField('제목', max_length=200)
    content = models.TextField('내용')
    create_date = models.DateTimeField('등록날짜')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # on_delete=models.CASCADE 이 뜻은 이 답변과 연결된 질문(Question)이 삭제될 경우 답변(Answer)도 함께 삭제된다는 뜻
    content = models.TextField('내용')
    create_date = models.DateTimeField('등록날짜')

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):  # QuestionForm은 모델 폼을 상속함 # 외워야함
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']
        labels = {  # 질문등록화면에 표시되는 subject, content를 영문이 아닌 한글로 표시하고 싶은 경우 아래처럼 labels 속성 지정해주기
            'subject': '제목',
            'content': '내용',
        }


# Question의 속성 id, subject, content, create_date중 질문등록글을 작성할 때 빈칸
# 이어서는 안될 속성인, subject와 content를 fields에 포함시켜주면
# 서버 접속 창에서 둘 중에 하나라도 안적었을 시 "이 입력란을 적어주세요"라며 안내창이 뜸
# 즉, form은 우리가 저런 것들을 스스로 구현하지 않아도 fields에 해당 속성을 넣어주기만
# 하면 둘 중에 하나라도 빈칸으로 저장할 수 없도록 하는 기능을 제공함
# (둘 다 무조건 입력하도록 필수 기재사항을 만들어놓는 기능 제공)

class AnswerForm(forms.ModelForm):  # QuestionForm은 모델 폼을 상속함 # 외워야함
    class Meta:
        model = Answer  # 사용할 모델
        fields = ['content']
        labels = {  # 답변등록화면에 표시되는 content를 영문이 아닌 한글로 표시하고 싶은 경우 아래처럼 labels 속성 지정해주기
            'content': '답변내용',
        }

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm


def index(request): # 자바에서 rq와 같은 것
    """
    pybo 목록 출력
    """
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list} # {'값':키} # question_list 변수에 question_list의 값을 넣겠다.
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
     pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)


def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid(): # 폼이 유효하면
            # 폼을 먼저 임시저장해서 answer에 넣자 => 임시저장 안하고 그냥 저장해버리면 create_date에 값이 없다는 오류 생김(현재QuestionForm에는 답변등록날짜 속성이 없기 때문에! 그래서 먼저 임시저장 후 answer객체를 리턴받아 create_date에 값을 설정 후 save()로 실제 저장해줌)
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

# redirect(URL로 이동할 경로, 넘겨줄 거 있으면 넘겨줄거 쓰기)
# redirect는 URL로 이동
# URL 로 이동한다는 건 그 URL과 연결된 views 가 다시 실행될테고
# views와 연결된 함수의 return값을 보고 render를 할지 다시 redirect 할지 결정할 것



def question_create(request):
    """
    pybo 질문등록
    """
   # form = QuestionForm()
   # return render(request, 'pybo/question_form.html', {'form':form})
# render는 템플릿을 불러옴
# render(request, 불러오고 싶은 template_name, context는 템플릿인 pybo/question_form.html에 전달할 데이터를 Dictionary로 전달)
# 이때, Dictionary의 key는 pybo/question_form.html에서 사용할 템플릿변수명이 되고,
# value는 전달하는 내용을 넣어주면 됨

# render함수 vs redirect 함수
# 이 두 함수의 차이점은 render의 경우 내가 가진 templates에 data를 넣어 보내고 싶을 때 이용하고,
# redirect는 내가 가진 templates뿐만 아니라 절대 url로 이동하고 싶을 때에도 이용 가능

# question_create 함수를 아래와 같이 수정함
    if request.method == 'POST':
        form = QuestionForm(request.POST)  # request.POST를 인수로 받을 경우에는 request.POST에 담긴 subject와 content의 값이 QuestionForm의 그 둘 속성에 자동으로 저장돼서 객체 생김
        if form.is_valid(): # form이 유효한지를 검사 * valid 뜻 : 유효하다면
            question = form.save(commit=False) # form으로 Question 데이터를 저장하기 위한 코드 * commit=False는 임시저장을 의미
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index') # redirect이므로 별칭 index로 이동하겠다.
    else: # 그게 아니면(즉, request.method가 POST가 아니면 )
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context) # 질문등록화면을 보여줘라

# GET 방식에서는 form = QuestionForm() 처럼 QuestionForm을 인수 없이 생성함.
# 하지만 POST 방식에서는 form = QuestionForm(request.POST) 처럼 request.POST를
# 인수로 생성함. request.POST를 인수로 QuestionForm을 생성할 경우에는
# request.POST에 담긴 subject, content 값이 QuestionForm의 subject, content 속성에
# 자동으로 저장되어 객체가 생성된다.
# request.POST에는 화면에서 사용자가 입력한 내용들이 담겨있음

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

</html>

templates/pybo/question_detail.html
<!-- 기본 틀이 되는 base.html을 상속하여 question_detail에 적용해줌-->
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %} <!-- base.html 상속해주기-->

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form-my-3">
        {% csrf_token %} <!--form 태그 아래에는 보안 적용하는 csrf 써주기-->
         <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
        <!-- 사용자가 질문등록화면으로 넘어와 제목과 내용에 값을 기입하고
         "저장하기"버튼을 클릭하면 동일한 /pybo/question/create/ 페이지가
         POST 방식으로 요청됨. (post는 '부치다, 제출하다'라는 의미로 사용자가
         해당 항목에 값을 추가 또는 수정하여 서버로 제출하는 것이 post 방식)-->
    </form>
</div>
{% endblock %}

<!-- {{내용}}는 안의 "내용"을 출력하라는 의미-->

templates/pybo/question_list.html
<!-- 기본 틀이 되는 base.html을 상속하여 question_list에 적용해줌-->
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>

    </table>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
    <!-- 위와 같이 링크를 통해 페이지를 요청할 경우에는 무조건 GET 방식이 사용됨
     말 그대로 사용자에게 질문 등록할 화면을 보여주는 것이기 때문에 GET
     참고로 만약, 사용자가 값을 적어서 제출한다면 그건 POST 방식임-->
</div>

{% endblock %}